### ISSUE TITLE
Display an error message when incorrect JSON file format is imported

### ISSUE THREAD

**Issue by jdaguil** [nexB/aboutcode-manager#114]
No user feedback is provided when an incorrectly formatted JSON file is selected for import. 

One example where the JSON file is incorrect is when it has an object with an erroneous trailing comma following its last attribute value. For example, `scan_errors` in the example below

```
"files": [
  {
    "path": "thirdparty/bootstrap-2.3.2.zip",
    "type": "file",
    "name": "bootstrap-2.3.2.zip",
    "extension": ".zip",
    ..
    ..
    "is_script": false,
    "scan_errors": [],
  }
  ..
  ..
]
```

**Comment by jdaguil** [comment]
@johnmhoran I mentioned looking for a JSON validator but a better solution is probably to catch the exception and alert the user. Based on the issue description, the exception is probably being swallowed. My guess is that it's probably throwing on the JSON.parse

**Comment by johnmhoran** [comment]
Thanks @jdaguil .  

I’ve run a `git pull` to update my local version of ScanCode and scanned the `zlib-1.2.11` library to generate a fresh JSON file for testing purposes.  

Given your reference to `JSON.parse`, I examined our main .js files for the use of `JSON.parse` (`aboutCodedataTables.js`, `aboutCodeDB.js`, `aboutCodeNodeView.js`, `componentDataTables.js`, `export-to-dejacode.js`, `nodeview.js`, `renderer.js`, `scandata.js`, and `main.js`).  I’ve identified just one use of `JSON.parse` in those files: in `aboutCodeDB.js`, in this block beginning on line 398:

```
    // Stores an object as a json string internally, but as an object externally
    static jsonDataType(attributeName) {
        return {
            type: Sequelize.STRING,
            get: function() {
                return JSON.parse(this.getDataValue(attributeName));
            },
            set: function(val) {
                return this.setDataValue(attributeName, JSON.stringify(val));
            }
        }
    }
```

My testing suggests this block is not called until after the incoming JSON file has been accepted as properly formatted, i.e., the user (1) selects `Import JSON File` in the `File` menu, (2) in the `Open a JSON File` dialog: selects a JSON file and clicks `Open`, and (3) in the `Save a SQLite Database File` dialog: selects a destination folder, adds a name for the sqlite file and clicks `Save`.  I see from the placement of a series of  `console.log()` calls that if the JSON file is not properly formatted -- e.g., if I add a trailing comma or some other extraneous string or punctuation -- AboutCode Manager stalls at the end of step 2, and the `aboutCodeDB.js` block above is not reached, so we can’t catch a malformed JSON file there.

Based on my testing, the right location to catch a malformed incoming JSON file seems to be in `renderer.js`, inside `ipcRenderer.on('import-JSON', function () . . .` (the block begins on line 485), which is invoked from `main.js` when the user selects `Import JSON File`.  More specifically, the `$.getJSON` function (starts on line 498) seems to be where a malformed JSON file hangs up the process:
* If I place `console.log()` calls immediately before and immediately after the first line of the `$.getJSON` function (line 498) and try to import a well-formed JSON file, both calls are reached.  
* If I add a trailing comma to the JSON file, the first `console.log()` call is reached, but the call immediately after the first line of the `$.getJSON` function is not reached.

But catching the culprit and notifying the user has been elusive thus far.  A number of StackOverflow discussions and other posts, articles etc. suggest using `JSON.parse`, with a try/catch, to test the JSON formatting, so I’ve tried something like this to wrap around the contents of (i.e., inside) the `$.getJSON` function (the block I'm referring to as the  "contents" starts on line 500 with a comment):

```
function testJSON(incomingJSON) {
    try {
        console.log('Inside getJSON step 1');
        JSON.parse(incomingJSON);
        console.log('Inside getJSON step 2');
        return true;
    }
    catch (error) {
        console.log('The error is: ' + error);
        return false;
    }
}

if (testJSON(json)) {
    [contents of $.getJSON]
}
else {
    console.log('The JSON is not well formed.');
}
```

Unfortunately, this did not trap the malformed JSON file.
* If I add a trailing comma to the JSON file, the app stalls before reaching the try/catch -- as was the case with the `console.log()` call mentioned above.
* With the malformed JSON, if instead I add a similar try/catch immediately before the `$.getJSON` function (wrapping the entire `$.getJSON` function), the console shows an error: ` Uncaught ReferenceError: json is not defined` -- `json` doesn’t get defined until we’re inside the `$.getJSON` function.

That seems to rule out `JSON.parse` as a way to identify malformed JSON and alert the user.  As an aside, it looks like `JSON.parse` would not work inside `$.getJSON` for another reason: if I add this try/catch inside `$.getJSON` and try to import a well-formed JSON file, the try/catch is reached but throws an error: `SyntaxError: Unexpected token o in JSON at position 1`.  Research suggests that’s because the incoming JSON has already been parsed by this point.  

I’ll look at `.fail()` as a possible solution . . . .

**Comment by jdaguil** [comment]
@johnmhoran Oops, `$.getJSON()` is what I meant. Sorry, it was late! 😛

**Comment by johnmhoran** [comment]
NP @jdaguil !  Gave me a chance to dig into the code a bit, learn about `JSON.parse`, locate the likely function through `console.log()` tests, and learn a bit about `$.getJSON()` including the `.fail()` and other callbacks.  :+1:
