### ISSUE TITLE
Improve speed of file explorer node expansion and collapse

### ISSUE THREAD

**Issue by pombredanne** [nexB/aboutcode-manager#188]
The tree feels smoochy. This is likely a setting n the library. Making it expand and collapse without delay would be much better IMHO

**Comment by jdaguil** [comment]
Are you talking about the expansion and collapse of nodes in the node view? Or are you talking about expansion and collapse of the directories and files in the left tree pane?

**Comment by pombredanne** [comment]
@jdaguil The left tree pane, explorer or finder-like with files and directories. Side note: I really like that this is keyboard friendly btw :+1: 

 .

**Comment by jdaguil** [comment]
@pombredanne can you quantify with some example times? We previously had it load everything at once, but then there was a delay before the tree showed up after loading a file. We switched to lazy loading so that the tree would show up immediately regardless of how big the SQLite file is. This made load times faster, and we could also save ram for large databases. Likely, if it's taking a long time it's because there's a lot of files in the tree, so loading them all in memory would increase ram usage and slow down the initial SQLite load time.

**Comment by pombredanne** [comment]
This is not a matter of lazy loading IMHO, but rather some setting on the tree UI lib that does "smooth" collapse and expand, as some sorts of springy visual effect trying to be nice, but this is not nice IMHO. There is some delay or effect that can likely be disabled.

**Comment by jdaguil** [comment]
I've just pushed a fix for what I think you are referencing. I misunderstood what you were saying until the last iteration.
