### ISSUE TITLE
Ability to resize the views

### ISSUE THREAD

**Issue by jdaguil** [nexB/aboutcode-manager#21]
It would be nice to be able to resize the views (node view and table view)

**Comment by majurg** [comment]
Another thing to note: Resizing the `aboutcode-manager` application window expands the table view correctly, but in the node view, the viewport window size stays static. See the attached picture:

 
![screen shot 2017-04-27 at 9 54 24 am](https://cloud.githubusercontent.com/assets/7485204/25494739/89229918-2b2f-11e7-8d8c-67d9427255fd.png)


You can see from this image that the node-view viewport x-axis does not extend with the application window. Additionally, the node-view viewport y-axis also stays static regardless of window size.

**Comment by johnmhoran** [comment]
@jdaguil When we speak of resizing the node view and table view, I take that to mean creating a vertical divider between the tree view and the node/table views, which the user can drag to the left or the right, altering the size of the views on either side of the divider.  Is that correct?

**Comment by jdaguil** [comment]
@johnmhoran Yes, that's the basic idea. Possibly a vertical slider because the user needs to be able to grab something to resize it, but other options are also welcome.

**Comment by johnmhoran** [comment]
Thanks @jdaguil .

**Comment by johnmhoran** [comment]
@jdaguil  Brief update:

I've been working with the splitter (using [Split.js](https://github.com/nathancahill/Split.js/)), focused on displaying the Component Summary at full-width.  The issue: when the user selects the Component Summary View, the table is displayed at less than full-width, and the vertical splitter (known as the `gutter`) remains visible on the left side of the screen.  I don’t yet have a complete solution, but I have an idea (see last paragraph).

To create an instance of `split.js`, we identify the divs we want to split horizontally and provide several other settings including the relative percentage widths (these would be heights for a vertical split) of the divs, e.g., 

```
    const instance = Split(['#leftCol', '#tabbar'], {
        sizes: [18, 76],
        minSize: 200,
        gutterSize: 5
    });
```

When the user resizes the divs, `split.js` “remembers” the widths of the divs.  And therein lies the challenge.

To display the Component Summary full-width, we need to expand the div in which the Component Summary sits -- the `tabbar` div -- when the user selects the Component Summary view.  I have figured out how to set a nice wide width when the user selects the Component Summary view, but because this is the same div in which the Table View and the Node View are located, changing the `tabbar` div width for the Component Summary View changes the `tabbar` div width that the Table and Node Views use when they are subsequently selected.

I’ve tried several approaches, including destroying and reinstantiating the splitter as different views are selected, but these approaches have been unsatisfactory.  I’ve also cloned the `tabbar` div and moved the Component Summary to this new renamed div, hiding and displaying it as necessary.  This had some beneficial effects -- including removing the unwanted `gutter` in the Component Summary View -- but also came with several bugs of its own.  For now that’s on the back burner.

Working with our current div structure, it occurs to me that I might be able to use local storage to store the correct widths for the Table and Node views (including any changes made when the user resizes), saving and retrieving the values as necessary.  I’m going to pursue this avenue unless you suggest otherwise.

**Comment by johnmhoran** [comment]
@jdaguil Working on my next commit: 

The Component Summary view now displays the DataTable at full-width without disturbing any resizing the user may have done to the Tree and Table/Node views.  
* We grab the splitter’s respective div widths (for the Tree and Table/Node views) each time the user resizes and save the widths as JSON in HTML5 local storage.  
* When a user navigates to the Component Summary view, the vertical splitter (the `gutter`) is no longer visible (we change its CSS) and we apply a different div-width setting.  
* When the user returns to the Table/Node views, we again change the `gutter` CSS to make it visible and retrieve and apply the div widths from local storage or, if there are none, we apply the default config.

On Windows 10 (not yet tested on Ubuntu 16.04), local storage persists across browser sessions and reboots, so by default any saved resizing will be applied when the user relaunches AboutCode Manager.  
* I’ve also created the option to clear any saved resizing when AboutCode Manager is closed, in which case on launch the default splitter div widths are applied.
* For now, that option is available only as hard-coded, though we could create a configuration page/modal where the user could select a radio button: save/don’t save resizing.  (We might want to use local storage for other user config options as well.)

Question: Unless/until we provide the option to the user, do you prefer (a) persisting saved resizing or (b) clearing saved resizing when AboutCode Manager is closed?

BTW, I’ve added `split.js` to `assets/js/` and we now call that copy in `index.html` (rather than from `node_modules . . .`).  I’ll add `.ABOUT` and `.LICENSE` files in a separate commit.

**Comment by jdaguil** [comment]
@johnmhoran IMHO, I would clear it. The position of the splitter depends on what you are displaying, and when you restart the app you are not displaying data yet. In the future, if it's decided to save more of the app state (i.e. you open the app with the previous file, tab, and search saved), then it might make sense to save the slider position at that time.

**Comment by johnmhoran** [comment]
Excellent, will do.  Thanks @jdaguil .

**Comment by jdaguil** [comment]
Awesome! 👍
