### ISSUE TITLE
Do not grey out background when creating a component

### ISSUE THREAD

**Issue by jdaguil** [nexB/aboutcode-manager#22]
The modal popup in the conclusion view darkens the background when it appears. It would be useful to be able to see the node tree without a grey shadow over it.

**Comment by johnmhoran** [comment]
@jdaguil   Removing the gray background should be trivial, but what are the overall design/usability goals?  For example, even if we remove the gray background, it’s possible that only a portion of the node tree would be visible, and because this is a modal, the user cannot move the node tree for greater visibility while the modal is open.  

More broadly: What types of functionality and information would we like the user to have access to while the modal is open?

**Comment by jdaguil** [comment]
Agreed @johnmhoran. This is the default behavior of Bootstrap it can probably be changed with CSS. This issue was a suggestion by @pombredanne.

**Comment by majurg** [comment]
@pombredanne removing the `background-color` CSS attribute of the `modal-backdrop` Bootstrap CSS id gives the following results:
![screen shot 2018-02-08 at 15 11 06](https://user-images.githubusercontent.com/7485204/36003323-516fb1e6-0ce2-11e8-817e-d9c5170b9c1e.png)


@pombredanne Is that what you were looking for?

**Comment by majurg** [comment]
Merged in the initial change that simply removes the grey background. Other tickets can be opened if we need the functionality that @johnmhoran mentions above.
