### ISSUE TITLE
Support launching ScanCode scans

### ISSUE THREAD

**Issue by jdaguil** [nexB/aboutcode-manager#23]
Being able to launch and control scans from the app would be a great new feature.

**Comment by jdaguil** [comment]
For a small scan this is a nice to have. For a large scan that would take several hours, it's unclear how much benefit we would gain from running this in AboutCode Manager versus the terminal. Especially when you consider how long a ScanCode scan takes versus how long it takes to import it into AboutCode Manager. Anecdotally, I've noticed it takes significantly longer to scan a directory than it does to import the JSON file into the app. Furthermore, other options exist to reduce the time further. For example, outputting a SQLite file directly from ScanCode. I'd recommend getting some data on the timing of scan versus import before putting a lot of effort into this.

**Comment by mjherzog** [comment]
The benefit here is primarily to allow a user to work from the GUI rather than the command line. My expectation is that this function would launch a Scan from a command line in the background with some mechanism to alert the user when the Scan has completed. There is clearly much more design work needed.

**Comment by jdaguil** [comment]
Yes, I think we could get something working fairly quickly that just launches a scan from the command line. The main issues will be determining where the ScanCode executable lives (this would probably have to be manually input by the user), and displaying something useful while the scan is running. As a start, we could mimic the output of the scan, but eventually we would probably want to parse that to display some kind of progress bar. 

Also, one design challenge that I think is particularly important is that we would want to make sure the scanning does not block the UI process. We will have to handle what happens if a user started doing other work with the app after the scan starts.

**Comment by mjherzog** [comment]
Perhaps this feature should only be enabled where you run the scans from an instance of ScanCode.io.

**Comment by mjherzog** [comment]
Closing this ticket because it s not consistent with our roadmap for AbC Manager. The logistics of connecting to whatever server will run ScanCode is very complex and not the best use of AbC Manager as a desktop application.  We will focus AbC Manager enhancements on the analysis of Scan files and creating Conclusions.
