### ISSUE TITLE
Add the ability to reset filter and searches

### ISSUE THREAD

**Issue by pombredanne** [nexB/aboutcode-manager#241]
### Description
When I navigate scan results I often end up with no data because previous filters or searches are still active.
I would like to be able to reset all active filters and searches at once to avoid this annoyance.

**Comment by mjherzog** [comment]
When working with column filters in the Table View, it can be very difficult to track which filters are applied especially since we currently have "all" rows shown as null/blank in the filter fields. It would be generally useful to have menu option to turn filters off at a global level (somewhat similar to turning off filters in Excel or similar spreadsheet programs). The current workaround to exit AbC Manager and reload the SQLite file is cumbersome.

**Comment by majurg** [comment]
#269 adds functionality to clear all column filters and the global search box. Closing this ticket.
