### ISSUE TITLE
Fix message when no components are present in summary list for DejaCode import

### ISSUE THREAD

**Issue by jdaguil** [nexB/aboutcode-manager#40]
In the component summary view, when no components are presented in the list and a user attempts to submit components to DejaCode, the message _"Components submitted to DejaCode"_ appears.

**Comment by johnmhoran** [comment]
@jdaguil  Thus far I’ve been unable to access the components table or the `Upload Components` button inside the `Component Summary View` and test whether the table is empty.  

In `index.html` I see a “skeletal” table (i.e., no rows): the table (`id="components-table"`) (https://github.com/nexB/aboutcode-manager/blob/7a9a0ce4aae1be077826450a089e88990701ad6a/index.html#L94) sits inside a div (`id="component-container"`) that is hidden by default.  Ideally I’d like to work with the click event for the `Upload Components` button, but there’s no trace of the button in `index.html`, and no click event for it in `renderer.js`.

The only reference to the button I’ve found is in `componentDataTables.js`, where the `ComponentDataTable` class is defined.  The `Upload Components` button is defined in lines 50-53 (https://github.com/nexB/aboutcode-manager/blob/7a9a0ce4aae1be077826450a089e88990701ad6a/assets/js/componentDataTables.js#L50), and its modal-opening behavior is defined in lines 21-27 (https://github.com/nexB/aboutcode-manager/blob/7a9a0ce4aae1be077826450a089e88990701ad6a/assets/js/componentDataTables.js#L21).  It’s not clear to me how this works to create the button and enable it to open the `componentExportModal`, but it appears that is precisely what the code does.

As noted above, ideally I’d like to work with that button’s click event and test whether the table is empty, but cannot find how to do so.  Failing that, I thought I might be able to work with the `Submit` button in the `Upload Components to DejaCode` modal.  

In `renderer.js`, we define a constant for the components table (`const componentsTable = new ComponentDataTable("#components-table", aboutCodeDB);`) (https://github.com/nexB/aboutcode-manager/blob/7a9a0ce4aae1be077826450a089e88990701ad6a/assets/js/renderer.js#L28).  Based on my research, I thought I could use the `Submit` button-click event to test whether the `componentsTable` is empty and, if so, trigger an alert, but no success thus far.  

Here's how I structured the test in `renderer.js` immediately inside the button-click function for the `Submit` button (which begins on line 648 (https://github.com/nexB/aboutcode-manager/blob/7a9a0ce4aae1be077826450a089e88990701ad6a/assets/js/renderer.js#L648)):
```
submitComponentButton.on("click", function () {
    if (componentsTable.data().length == 0) {
        alert("You cannot complete the upload process because the components table is empty.");
    } 
```

However, the console shows an error: `Uncaught TypeError: componentsTable.data is not a function`.  It occurs to me that since we’re using a `ComponentDataTable` class, perhaps I need to modify the class in order to access the button and/or test whether the table is empty.  

What is the correct way to access the `Upload Components` button and the `componentsTable` as well?

**Comment by jdaguil** [comment]
@johnmhoran 

> What is the correct way to access the Upload Components button

This is handled through the DataTables "buttons" plugin. Check out this doc:

https://datatables.net/reference/option/buttons.buttons.action

> and the componentsTable as well?

Typically, you don't want to rely on the DataTable to access the data because a DataTable is only responsible for showing a portion of the full set of data. In general, all data access should go through the database instead. For this case you will want to look at the [`Component`](https://github.com/nexB/aboutcode-manager/blob/develop/assets/js/aboutCodeDB.js#L52) table in `AboutCodeDB`, which is the table that stores the component data.  Have a look at [`findAllComponents()`](https://github.com/nexB/aboutcode-manager/blob/develop/assets/js/aboutCodeDB.js#L78) in `AboutCodeDB`, which will return a promise with all components in the `Component` table.
