### ISSUE TITLE
Add Summary Views for Scans

### ISSUE THREAD

**Issue by mjherzog** [nexB/aboutcode-manager#99]
We need to offer some summary views for scans, particularly for Licenses and Copyrights.
Some good starting points to consider are:
- Bar charts from ScanCode HTML App
- TreeMaps from ScanCode.io
- Table lists from ScanCode.io

There should be many other options / ideas to consider from D3, such as Bubble Charts.

**Comment by majurg** [comment]
Some ideas to throw out:

**Comment by majurg** [comment]
Some ideas to throw out:
- bubble chat for license summary, where the bubble is a license key and the bubble size corresponds to the # of times that license key appears in the scan results
- weighted tree graph for node view, where the weights could be # of files, # of license occurrences, license categories

**Comment by mjherzog** [comment]
The Dashboard prototype with pie-charts is a good look for a summary dashboard page.  Since we have no way to predict the data distribution within a scan, we want to use a simple paradigm for presenting the summaries.  I recommend that we apply a Top 10 approach for summary charts - i.e. show the Top 9 values for license, copyright holder etc with the 10th bucket/slice for others.  If  a data element (like License Categories) has fewer than 10 values then we can use that data directly.

**Comment by majurg** [comment]
I really like the pie-chart summary view; It would be awesome to have a similar chart for packages. 

For instance, have a breakdown by package type or package primary language would go a long way during analysis. That, along with a number (i.e. the # of jars, the # of npms) would also be a good addition, perhaps incorporated into the pie-chart itself. 

For the above additions, the needed information should be included in a `scancode -p` scan. If it isnt, we should open a ticket(s) in scancode because that information is very very useful for the quote phases of a lot of audits.
